# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: greet.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'greet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgreet.proto\x12\x05greet\"\xad\x01\n\rHelloRequest1\x12\x14\n\x0ctv_show_name\x18\x01 \x01(\t\x12\x14\n\x0ctv_show_year\x18\x02 \x01(\x05\x12\x14\n\x0c\x65pisode_name\x18\x03 \x01(\t\x12\x16\n\x0e\x65pisode_season\x18\x04 \x01(\x05\x12\x16\n\x0e\x65pisode_number\x18\x05 \x01(\x05\x12\x16\n\x0e\x63haracter_name\x18\x06 \x01(\t\x12\x12\n\nactor_name\x18\x07 \x01(\t\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\x83\x01\n\x07Greeter\x12\x32\n\x08SayHello\x12\x13.greet.HelloRequest\x1a\x11.greet.HelloReply\x12\x44\n\x18StreamFromClientSayHello\x12\x13.greet.HelloRequest\x1a\x11.greet.HelloReply(\x01\x42\x0e\xaa\x02\x0bGrpcGreeterb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\013GrpcGreeter'
  _globals['_HELLOREQUEST1']._serialized_start=23
  _globals['_HELLOREQUEST1']._serialized_end=196
  _globals['_HELLOREQUEST']._serialized_start=198
  _globals['_HELLOREQUEST']._serialized_end=226
  _globals['_HELLOREPLY']._serialized_start=228
  _globals['_HELLOREPLY']._serialized_end=257
  _globals['_GREETER']._serialized_start=260
  _globals['_GREETER']._serialized_end=391
# @@protoc_insertion_point(module_scope)
